* Some ideas
- Ability to group notes inside headings? Inserts always outside, but the user is able to
  move them anywhere they want, still scrolling automatically and working with M-n, M-p...

- Import utility:  have a folder  associated with a notes  file that holds  all documents;
  then, maybe something like ~org-noter-update-documents~ which will check if any document
  already  on the  notes  file is  missing  and mark  it  as such  (put  *MISSING* on  the
  heading?), and import  every new document from  the documents folder to  the file, using
  the folder hierarchy as structure. An idea is to open each file on a side buffer and ask
  for the respective name of the heading, to ease the renaming.
  - Should this command also import things like images and text files?

- Should the package be able to annotate other types of files???

- Add commands like ~org-noter-rename~ and ~org-noter-delete~ which work on the document
  file instead of the heading?.. ~org-noter-delete~ could delete all documents in a
  subtree, maybe with a prefix arg?

- When opening an already open session, if inside a specific note, go there!
